In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv("/content/Social_Network_Ads.csv") 
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
df.shape

(400, 3)

In [8]:
X = np.asarray(df[['Age','EstimatedSalary']])
X[0:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [11]:
y = np.asarray(df[['Purchased']])
y[0:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

## Chuẩn hóa dữ liệu

In [12]:
X_nor = preprocessing.StandardScaler().fit(X).transform(X)
X_nor [0:5]

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059]])

## Chia dữ liệu thành 2 tập train và test

In [14]:
from sklearn.model_selection import train_test_split
#Dựa trên dữ liệu chưa được chuẩn hóa
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4)
print("Train set without normalize: ", X_train.shape, y_train.shape)
print("Test set without normalize: ", X_test.shape, y_test.shape)
#Dựa trên dữ liệu đã được chuẩn hóa
X_train_nor, X_test_nor, y_train_nor, y_test_nor = train_test_split(X_nor, y, test_size = 0.2, random_state = 4)
print("Train set with normalize: ", X_train_nor.shape, y_train_nor.shape)
print("Test set with normalize: ", X_test_nor.shape, y_test_nor.shape)



Train set without normalize:  (320, 2) (320, 1)
Test set without normalize:  (80, 2) (80, 1)
Train set with normalize:  (320, 2) (320, 1)
Test set with normalize:  (80, 2) (80, 1)


In [15]:
from sklearn.linear_model import LogisticRegression
#dựa trên dữ liệu chưa được chuẩn hóa
LR = LogisticRegression(C=0.01, solver="liblinear").fit(X_train, y_train)
LR

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='liblinear')

In [19]:
#dựa trên dữ liệu đã được chuẩn hóa
LR_nor = LogisticRegression(C=0.01, solver="liblinear").fit(X_train_nor, y_train_nor)
LR_nor

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='liblinear')

In [18]:
y_hat = LR.predict(X_test)
y_hat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
y_hat_nor = LR_nor.predict(X_test_nor)
y_hat_nor

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

## So sánh F1 score

không chuẩn hóa dữ liệu

In [20]:
from sklearn.metrics import f1_score
f1_score(y_test, y_hat, average="macro")

0.4244604316546763

Chuẩn hóa dữ liệu

In [21]:
f1_score(y_test_nor, y_hat_nor, average="macro")

0.8568872987477638

# có chuẩn hóa dữ liệu hiệu quả hơn so với không chuẩn hóa dữ liệu